### ISSUE TITLE
这种使用方式未通过 music_info: { type: String, default: '', required: false } 

### ISSUE THREAD

**Issue by 965390267** [MatchOvO/param-validator.js#1]
查看源码 _typeof 方法中 return  val && val.constructor ? val.constructor.name : String(val) 校验空支付返回了 undefined ，第一个val 应该改成(val!==undefined && val !== null)

**Comment by MatchOvO** [comment]
非常感谢提交的issue，这个问题将会很快被调查和改正，新的更正将会伴随着即将发布的1.4版本并伴随着更多新的能力.

**Comment by MatchOvO** [comment]
const model = {
    name:{
        type: String,
        default: '',
        required: false
    }
}

const user = {
    name: undefined
}
根据调查，是否是在遇到以上的使用场景时无法校验通过？如果是，这个问题是源于ParamValidator.js设计的时候将undefined单独分为了一种数据类型（详情可以查阅文档中other类型的部分），这意味着如果被校验的数据在对象中某个字段被指明为undefined则被认为是undefined类则会与model中指定的String类发生冲突则被认为是不通过，这个问题在当前的版本最直接的解决办法是将model中type属性改为[String, undefined]，不过我们确实意识到目前的设计会带来一些混淆，并且即使使用了以上方法，default值也不会生效，不过这个设计问题将会很快得到解决，请关注下一个版本更新。除此之外希望能提供在校验怎么样的数据时无法通过，以快速定位问题并帮助我们意识到我们忽略了哪些方面的使用场景。再次感谢你的分享。

**Comment by MatchOvO** [comment]
在最新版本1.4.0中已对逻辑进行了优化，新的README文档中有所提及，更详细的对此部分的进一步尝试等待后续官网文档的更新，新版本也有很多新特性，enjoy！并且此条issue将被关闭。
